import type { Project } from "./types";

export const projects: Project[] = [
	{
		id: "1",
		slug: "bluesky",
		name: "Bluesky",
		description:
			"Decentralized social network built on ATProto. The flagship ATProto application offering a Twitter-like experience.",
		icon: "🦋",
		iconUrl: "/icons/bluesky.png",
		url: "https://bsky.app",
		alternativeTo: ["Twitter/X"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://github.com/bluesky-social",
		tags: ["social", "client", "microblogging"],
	},
	{
		id: "2",
		slug: "deer",
		name: "Deer",
		description:
			"Fork of the Bluesky client with enhanced features and customization options.",
		icon: "💬",
		iconUrl: "/icons/deer.png",
		url: "https://deer.social",
		alternativeTo: ["Twitter/X"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://github.com/a-viv-a/deer-social",
		tags: [
			"social",
			"client",
			"microblogging",
			"customization",
			"alternative-client",
		],
	},
	{
		id: "3",
		slug: "graysky",
		name: "Graysky",
		description:
			"Native mobile client for Bluesky with smooth animations and native feel.",
		icon: "🌫️",
		iconUrl: "/icons/graysky.png",
		url: "https://graysky.app",
		alternativeTo: ["Twitter/X"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://github.com/mozzius/graysky",
		tags: ["social", "client", "microblogging", "mobile", "alternative-client"],
	},
	{
		id: "4",
		slug: "frontpage",
		name: "Frontpage",
		description: "Link aggregator built on ATProto.",
		icon: "📰",
		iconUrl: "/icons/frontpage.png",
		url: "https://frontpage.fyi",
		alternativeTo: ["Hacker News", "Reddit"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://github.com/likeandscribe/frontpage",
		tags: ["links", "aggregator", "discussion", "community"],
	},
	{
		id: "5",
		slug: "leaflet",
		name: "Leaflet",
		description: "Long-form blogging platform with markdown support.",
		icon: "📝",
		iconUrl: "/icons/leaflet.png",
		url: "https://leaflet.pub",
		alternativeTo: ["Medium", "Substack"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://tangled.org/leaflet.pub/leaflet",
		tags: ["blogging", "writing", "markdown", "long-form"],
	},
	{
		id: "6",
		slug: "smoke-signal",
		name: "Smoke Signal",
		description: "Event planning and RSVP platform.",
		icon: "📅",
		iconUrl: "/icons/smokesignal.png",
		url: "https://smokesignal.events",
		alternativeTo: ["Eventbrite"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://tangled.org/smokesignal.events/smokesignal",
		tags: ["events", "rsvp", "planning", "community"],
	},
	{
		id: "7",
		slug: "deck-blue",
		name: "deck.blue",
		description:
			"TweetDeck-style multi-column interface for Bluesky power users.",
		icon: "📊",
		iconUrl: "/icons/deckblue.png",
		url: "https://deck.blue",
		alternativeTo: ["TweetDeck"],
		isOpenSource: false,
		authType: "app-password",
		tags: ["social", "dashboard", "power-user", "columns"],
	},
	{
		id: "8",
		slug: "skyview",
		name: "Skyview",
		description:
			"Public thread reader for Bluesky that lets you share posts with anyone.",
		icon: "👁️",
		iconUrl: "/icons/skyview.png",
		url: "https://skyview.social",
		alternativeTo: ["Twitter/X Embeds"],
		isOpenSource: true,
		authType: "none",
		repositoryUrl: "https://github.com/badlogic/skyview",
		tags: ["viewer", "embed", "sharing", "public"],
	},
	{
		id: "9",
		slug: "bluecast",
		name: "Bluecast",
		description: "Voice message sharing and livestreaming platform.",
		icon: "🎙️",
		iconUrl: "/icons/bluecast.png",
		url: "https://bluecast.app",
		alternativeTo: ["Twitter/X Spaces"],
		isOpenSource: false,
		authType: "oauth",
		tags: ["voice", "audio", "livestream", "media"],
	},
	{
		id: "10",
		slug: "skyfeed",
		name: "SkyFeed",
		description: "Custom client and feed builder for Bluesky.",
		icon: "🐦",
		iconUrl: "/icons/skyfeed.png",
		url: "https://skyfeed.app",
		alternativeTo: ["Twitter/X Lists"],
		isOpenSource: true,
		authType: "app-password",
		repositoryUrl: "https://github.com/skyfeed-dev",
		tags: [
			"feeds",
			"curation",
			"filtering",
			"customization",
			"alternative-client",
		],
	},
	{
		id: "11",
		slug: "tangled",
		name: "Tangled",
		description:
			"Decentralized Git forge and collaboration platform with the ability to self-host.",
		icon: "🐑",
		iconUrl: "/icons/tangled.png",
		url: "https://tangled.org",
		alternativeTo: ["GitHub", "GitLab", "Gitea"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://tangled.org/tangled.org/core",
		tags: ["git", "forge", "collaboration", "community", "self-hosted"],
	},
	{
		id: "12",
		slug: "streamplace",
		name: "Streamplace",
		description: "Livestreaming platform built on ATProto.",
		icon: "📺",
		iconUrl: "/icons/streamplace.png",
		url: "https://stream.place",
		alternativeTo: ["Twitch"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://tangled.org/stream.place/streamplace",
		tags: ["video", "livestream", "media", "community"],
	},
	{
		id: "13",
		slug: "wisp",
		name: "Wisp",
		description: "Easy-to-use static site hosting and deployment.",
		icon: "🧚",
		iconUrl: "/icons/wisp.png",
		url: "https://wisp.place",
		alternativeTo: ["Netlify", "Vercel", "GitHub Pages"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://tangled.org/nekomimi.pet/wisp.place-monorepo",
		tags: ["hosting", "web", "deployment", "power-user"],
	},
	{
		id: "14",
		slug: "teal-fm",
		name: "teal.fm",
		description:
			'Music scrobbler. Currently under construction, but <a href="https://teal-relay-production.up.railway.app/">a 3rd-party live dashboard is available</a>.',
		icon: "🎵",
		iconUrl: "/icons/teal.png",
		url: "https://teal.fm",
		alternativeTo: ["Last.fm"],
		isOpenSource: true,
		authType: "none",
		repositoryUrl: "https://tangled.org/teal.fm",
		tags: ["music", "listening", "tracker"],
	},
	{
		id: "15",
		slug: "pipup",
		name: "PiPup",
		description:
			"Long-form blogging platform with rich formatting and diagramming support.",
		icon: "📝",
		iconUrl: "/icons/pipup.png",
		url: "https://pipup.social",
		alternativeTo: ["Medium", "Substack"],
		isOpenSource: false,
		authType: "oauth",
		tags: ["blogging", "writing", "markdown", "long-form"],
	},
	{
		id: "16",
		slug: "blento",
		name: "blento",
		description:
			"Minimal, friendly website building platform with optional self-hosting.",
		icon: "🟥",
		iconUrl: "/icons/blento.png",
		url: "https://blento.app",
		alternativeTo: ["Carrd", "Linktree"],
		isOpenSource: true,
		authType: "oauth",
		repositoryUrl: "https://github.com/flo-bit/blento",
		tags: ["hosting", "web", "builder", "self-hosted"],
	},
	{
		id: "17",
		slug: "nooki",
		name: "nooki",
		description: "Minimal discussion and community platform a la Reddit.",
		icon: "🩹",
		iconUrl: "/icons/nooki.png",
		url: "https://nooki.me",
		alternativeTo: ["Reddit"],
		isOpenSource: false,
		authType: "oauth",
		tags: ["links", "aggregator", "discussion", "community", "forums"],
	},
];

export function getAllTags(): string[] {
	const tagSet = new Set<string>();
	projects.forEach((project) => {
		project.tags.forEach((tag) => tagSet.add(tag));
	});
	return Array.from(tagSet).sort();
}

export function getAllAlternatives(): string[] {
	const altSet = new Set<string>();
	projects.forEach((project) => {
		project.alternativeTo.forEach((alt) => altSet.add(alt));
	});
	return Array.from(altSet).sort();
}

export function getProjectBySlug(slug: string): Project | undefined {
	return projects.find((p) => p.slug === slug);
}
